---
#@See https://dotlayer.com/how-to-use-an-ansible-playbook-to-install-wordpress/     #### FULL GUIDE FOR LAMP
- hosts: elk-server
  become: yes
  roles:
     - srv-prep
     - firewall
     - ssl
     - nginx
     - mariadb
     - php
     - wazuh
     - elasticsearch
     - logstash
     - kibana
     - elasticsearch-curator
...
