---
# -name: Install a list of packages to prepared Linux Server

- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: 'result.rc == 0'
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install a list of packages to prepared Linux Server
  yum:
    name:
      - epel-release
      - libselinux-python
      - policycoreutils
      - policycoreutils-python
      - vim
      - htop
      - tmux
      - wget
      - ntp
      - chrony
      - net-tools
      - git
      - net-tools
      - httpd-tools
    state: present
  become: true

- name: delegate to SELINUX handling subtask, if necessary
  include: set-selinux.yml
  when: nginx_in_selinux is defined and nginx_in_selinux == true

- name: copying ntp.conf file with owner and permissions
  copy:
    src: ntp.conf
    dest: /etc/ntp.conf
  become: true

- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  become: true
# Force all Handlers to run
- meta: flush_handlers

